version: 2
updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
    groups:
      all-deps:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: pre-commit
    directory: "/"
    schedule:
      interval: weekly
